Repository mysuperai/superai-sdk, pull requests merged in 2021-02, with the labels that each got.

#22 Apis jobs review
  setup.cfg
  setup.py
  superai/__init__.py
  superai/apis/jobs.py
Labels: feature

#20 Add Model API
  fixtures/cassettes/ai_api.yaml
  fixtures/cassettes/model_api.yaml
  pyproject.toml
  setup.py
  superai/apis/meta_ai/__init__.py
  superai/apis/meta_ai/meta_ai_graphql_schema.py
  superai/apis/meta_ai/model.py
  superai/apis/meta_ai/project_ai.py
  superai/apis/meta_ai/session.py
  superai/client.py
  superai/data_program/router/basic_router.py
  superai/data_program/router/router.py
  superai/settings.yaml
  superai/utils/pip_config.py
  tests/apis/test_meta_ai.py
Labels: enhancement

#24 Add video-bounding-box-keypoint example
  docs/examples/basic_vbbk.py
  superai/apis/data.py
  superai/data_program/project.py
  superai/data_program/task.py
  superai/data_program/utils.py
Labels: bug, enhancement, feature
